// The shell and the shared widget vocabulary, in both languages.
//
// `zh` is the source of truth: `strings/en.ts` types itself against these shapes, so a
// key added here and forgotten there is a compile error, not a Chinese sentence leaking
// into an English screen. Interpolated strings are functions carrying their parameters,
// which keeps the placeholder order free to differ between languages.

export const commonZh = {
  // --- the rail (main.ts) --------------------------------------------------------------
  navDeploy: "部署",
  navStatus: "状态",
  navVoices: "音色",
  navTrain: "训练",
  navSettings: "设置",
  brandRole: "语音合成控制台",
  railAria: "主导航",
  railRunning: "服务运行中",
  railStarting: "服务启动中",
  railStopped: "服务已停止",
  badgeRunning: "运行中",
  badgePendingDeploy: "待部署",

  // --- shared widgets (ui.ts) ----------------------------------------------------------
  revealInExplorer: "在文件资源管理器中显示",
  copied: (what: string) => `已复制${what}`,
  copy: (what: string) => `复制${what}`,
  clipboardFallback: "剪贴板访问受限：内容已选中，请按 Ctrl+C 复制",

  // --- toasts (toast.ts, state.ts) -------------------------------------------------------
  closeToast: "关闭提示",
  detectFailed: (detail: string) => `环境检测失败：${detail}`,
  loadPacksFailed: (detail: string) => `加载音色包列表失败：${detail}`,

  // --- durations (format.ts) -------------------------------------------------------------
  durSec: "秒",
  durMin: "分",
  durHour: "小时",
  durDay: "天",

  // --- form vocabulary (form.ts) ---------------------------------------------------------
  saved: "已保存",
  required: "此项必填",
  notANumber: "请输入有效数字",
  notAnInteger: "请输入整数",
  range: (min: string | number, max: string | number) => `取值范围：${min} - ${max}`,
  stepDown: (label: string) => `${label} 减少`,
  stepUp: (label: string) => `${label} 增加`,
  notSet: "未设置",
  pickColour: (label: string) => `${label} 取色`,
  clearField: (label: string) => `清除${label}`,
  clearInherit: "清除并继承上级配置",
  colourRequired: "颜色值不能为空",
  badHex: "格式支持 #rgb、#rrggbb 或 #aarrggbb",
  addTag: "添加项",
  removeTag: (tag: string) => `移除 ${tag}`,
  change: "更改",
  clear: "清除",
  capturing: "按下组合键，Esc 取消",
  provPack: "音色包内置",
  provConfig: "用户配置 (config.json)",
  provDerived: "自动推导 / 默认",
  viewSource: (label: string) => `查看源文件 · ${label}`,
  fileMissing: "文件不存在",
  cfgNotWritten: "配置文件尚未生成",
  cfgNotWrittenBody: "系统将在写入配置时自动创建该文件；当前使用内置默认配置。",
  fileUnreadable: "无法读取文件",
  fileUnreadableBody: "文件存在但内容暂不可读（可能正在被外部编辑器保存）。折叠并重新展开此栏即可重新加载。",
};

export const commonEn: typeof commonZh = {
  navDeploy: "Deploy",
  navStatus: "Status",
  navVoices: "Voices",
  navTrain: "Train",
  navSettings: "Settings",
  brandRole: "Voice synthesis console",
  railAria: "Main navigation",
  railRunning: "Service running",
  railStarting: "Service starting",
  railStopped: "Service stopped",
  badgeRunning: "Running",
  badgePendingDeploy: "Not deployed",
  revealInExplorer: "Show in File Explorer",
  copied: (what) => `${what} copied`,
  copy: (what) => `Copy ${what}`,
  clipboardFallback: "Clipboard access was blocked: the content is selected — press Ctrl+C to copy",
  closeToast: "Dismiss notification",
  detectFailed: (detail) => `Environment detection failed: ${detail}`,
  loadPacksFailed: (detail) => `Loading the voice-pack list failed: ${detail}`,
  durSec: "s",
  durMin: "min",
  durHour: "h",
  durDay: "d",
  saved: "Saved",
  required: "This field is required",
  notANumber: "Enter a valid number",
  notAnInteger: "Enter a whole number",
  range: (min, max) => `Range: ${min} – ${max}`,
  stepDown: (label) => `Decrease ${label}`,
  stepUp: (label) => `Increase ${label}`,
  notSet: "Not set",
  pickColour: (label) => `Pick ${label}`,
  clearField: (label) => `Clear ${label}`,
  clearInherit: "Clear and inherit the parent configuration",
  colourRequired: "A colour value is required",
  badHex: "Accepted formats: #rgb, #rrggbb or #aarrggbb",
  addTag: "Add item",
  removeTag: (tag) => `Remove ${tag}`,
  change: "Change",
  clear: "Clear",
  capturing: "Press a key combination, Esc to cancel",
  provPack: "Built into the voice pack",
  provConfig: "User config (config.json)",
  provDerived: "Derived / default",
  viewSource: (label) => `Source file · ${label}`,
  fileMissing: "File not found",
  cfgNotWritten: "The config file does not exist yet",
  cfgNotWrittenBody: "It is created the first time a setting is written; the built-in defaults apply until then.",
  fileUnreadable: "The file could not be read",
  fileUnreadableBody: "The file exists but its content is momentarily unreadable (it may be mid-save in an external editor). Collapse and reopen this section to load it again.",
};
