// The deploy screen, in both languages. `zh` is the source of truth; the `en` object
// types itself against it, so a key added above and forgotten below is a compile error.

export const deployZh = {
  title: "部署",
  transientTitle: "环境检查",
  backToStatus: "返回状态",

  envCard: "环境与依赖",
  detecting: "正在检测…",
  detectingAria: "正在检测系统运行环境",
  reusable: (size: string) => `${size} 可复用`,
  reuseGiB: (size: string) => `${size} 复用`,
  diskShort: "空间不足",
  notInstalled: "未安装",
  pickDir: "选择目录…",
  pickEngineDir: "选择本地已有引擎目录",
  pickModelsDir: "选择本地已有模型缓存目录",
  pickPacksDir: "选择本地已有音色包目录",
  reuse: "复用",
  ready: "就绪",
  rebuild: "需重建",

  engineSource: "引擎源码",
  pythonCuda: "Python 与 CUDA",
  pyLater: "将在「Python 环境」阶段创建",
  noCuda: "未检测到 CUDA，推理性能将显著受限",
  weights: (have: number, total: number) => `模型权重 ${have} / ${total}`,
  packsLabel: "音色包",
  packs: (n: number) => `音色包 ${n}`,
  needLine: (free: string) => `所需空间 · 可用 ${free}`,

  stepsTitle: "部署步骤",
  stepsTotal: (n: number) => `共 ${n} 步`,
  stepsTotalTime: (n: number, spent: string) => `共 ${n} 步 · 耗时 ${spent}`,
  stepIndex: (index: number, total: number, spent: string) => `步骤 ${index} / ${total} · 耗时 ${spent}`,
  remedyTitle: "排障指引",
  retryStep: "重试当前步骤",
  doneBytes: (size: string) => `已完成 ${size}`,
  doneItems: (n: number) => `已完成 ${n} 项`,
  interrupted: "已中断",

  jumpBottom: "跳转至底部",
  expandLog: "展开详细日志",
  collapseLog: "折叠详细日志",

  cancel: "取消",
  runningNow: "正在执行…",
  backgroundHint: "后台任务运行中，关闭窗口不影响执行",
  finish: "完成",
  checkOnly: "仅检测",
  reDetect: "重新检测",
  startDeploy: "开始部署",
  redeploy: "重新部署",

  startFailed: "启动任务失败",
  failedCount: (n: number) => `${n} 个步骤执行失败`,
  failedBody: (names: string) =>
    `「${names}」执行失败。排查问题后点击失败阶段的「重试当前步骤」，支持断点重试。`,
  cancelled: "已取消，未对环境进行修改",
  checkPassed: (n: number) => `环境检查通过：${n} 项就绪`,
  doneBanner: "部署完成，语音合成引擎已就绪",
  reusedCount: (n: number) => `${n} 个步骤已复用`,

  // The seven stages, named by outcome rather than in the engine's vocabulary.
  stagePreflight: "环境检查",
  stageEngine: "引擎源码",
  stageCodec: "音频编解码器",
  stageVenv: "Python 环境",
  stageModels: "模型权重",
  stageLayout: "写入配置",
  stageSmoke: "功能测试",

  statePending: "待执行",
  stateRunning: "进行中",
  stateOk: "完成",
  stateSkip: "已复用",
  stateFail: "失败",
};

export const deployEn: typeof deployZh = {
  title: "Deploy",
  transientTitle: "Environment check",
  backToStatus: "Back to status",
  envCard: "Environment & dependencies",
  detecting: "Detecting…",
  detectingAria: "Detecting the system environment",
  reusable: (size) => `${size} reusable`,
  reuseGiB: (size) => `${size} reused`,
  diskShort: "Low disk space",
  notInstalled: "Not installed",
  pickDir: "Choose folder…",
  pickEngineDir: "Choose a local engine directory",
  pickModelsDir: "Choose a local model-cache directory",
  pickPacksDir: "Choose a local voice-pack directory",
  reuse: "Reuse",
  ready: "Ready",
  rebuild: "Rebuild needed",
  engineSource: "Engine source",
  pythonCuda: "Python & CUDA",
  pyLater: "Created in the Python environment stage",
  noCuda: "No CUDA detected; inference will be significantly slower",
  weights: (have, total) => `Model weights ${have} / ${total}`,
  packsLabel: "Voice packs",
  packs: (n) => `Voice packs ${n}`,
  needLine: (free) => `Required · ${free} free`,
  stepsTitle: "Deployment steps",
  stepsTotal: (n) => `${n} steps`,
  stepsTotalTime: (n, spent) => `${n} steps · ${spent}`,
  stepIndex: (index, total, spent) => `Step ${index} / ${total} · ${spent}`,
  remedyTitle: "How to fix this",
  retryStep: "Retry this step",
  doneBytes: (size) => `${size} done`,
  doneItems: (n) => `${n} done`,
  interrupted: "Interrupted",
  jumpBottom: "Jump to bottom",
  expandLog: "Show detailed log",
  collapseLog: "Hide detailed log",
  cancel: "Cancel",
  runningNow: "Running…",
  backgroundHint: "The task keeps running in the background; closing the window does not stop it",
  finish: "Finish",
  checkOnly: "Check only",
  reDetect: "Re-detect",
  startDeploy: "Start deployment",
  redeploy: "Redeploy",
  startFailed: "Starting the task failed",
  failedCount: (n) => `${n} step(s) failed`,
  failedBody: (names) =>
    `"${names}" failed. After fixing the problem, press "Retry this step" on the failed stage - retries resume where the run stopped.`,
  cancelled: "Cancelled; nothing on the system was changed",
  checkPassed: (n) => `Environment check passed: ${n} item(s) ready`,
  doneBanner: "Deployment complete; the speech engine is ready",
  reusedCount: (n) => `${n} step(s) reused`,
  stagePreflight: "Environment check",
  stageEngine: "Engine source",
  stageCodec: "Audio codecs",
  stageVenv: "Python environment",
  stageModels: "Model weights",
  stageLayout: "Write config",
  stageSmoke: "Smoke test",
  statePending: "Pending",
  stateRunning: "Running",
  stateOk: "Done",
  stateSkip: "Reused",
  stateFail: "Failed",
};
