// The settings screen, in both languages. `zh` is the source of truth; the `en` object
// types itself against it, so a key added above and forgotten below is a compile error.

export const settingsZh = {
  title: "设置",
  dialog: "字幕外观",
  hotkeys: "快捷键",
  service: "服务",
  history: "版本",
  language: "语言",
  languageHint: "面板界面语言，切换后立即生效。",
  refresh: "刷新",

  annotationAboveLabel: "原文置于上方",
  annotationAboveHint: "设置发音原文的显示位置；关闭后固定置于下方。",
  revealLabel: "文字动效",
  revealTypewriter: "打字机",
  revealSweep: "扫光",
  revealFade: "淡入",
  revealHint: "打字机：按音频时长匀速显现；扫光：保持排版固定；淡入：按句子逐条淡入。",
  displaySecondsLabel: "停留时间",
  nameColorLabel: "说话人颜色",
  textColorLabel: "正文颜色",
  rubyColorLabel: "原文颜色",
  countdownColorLabel: "倒计时条颜色",
  toggleDialogLabel: "切换字幕显隐",
  toggleHoldLabel: "字幕常驻开关",
  idleStopSecsLabel: "显存释放延时",

  secondsUnit: "秒",
  rubyHint: "格式支持 #rgb、#rrggbb 或 #aarrggbb（前两位为透明度通道）。",
  hotkeyHint: "必须包含修饰键（Ctrl/Alt/Shift），避免拦截系统全局输入。",
  idleStopHint: "达到延时后释放模型缓存；持续空闲将终止引擎子进程。设为 0 表示常驻显存。",
  serviceNote: "修改将在下次服务启动时生效",

  defaultValue: "默认值",
  historyEmpty: "暂无改动记录",
  historyEmptyLead: "改动任何设置后，这里会出现可以还原的记录；记录写在 ",
  historyEmptyTail: "。",
  confirmRestore: "确认还原",
  cancel: "取消",
  restore: "还原",
  restored: (file: string) => `已还原 ${file}`,
  restoreFailed: (detail: string) => `还原配置失败：${detail}`,
  loadFailed: (detail: string) => `加载设置失败：${detail}`,
  loadHistoryFailed: (detail: string) => `加载改动记录失败：${detail}`,
  hotkeyFormat: "快捷键格式：修饰键+按键，如 Ctrl+Alt+D。",
};

export const settingsEn: typeof settingsZh = {
  title: "Settings",
  dialog: "Subtitle appearance",
  hotkeys: "Hotkeys",
  service: "Service",
  history: "History",
  language: "Language",
  languageHint: "The panel's interface language; a change applies immediately.",
  refresh: "Refresh",
  annotationAboveLabel: "Source line above",
  annotationAboveHint: "Where the spoken line's source text sits; below when off.",
  revealLabel: "Text effect",
  revealTypewriter: "Typewriter",
  revealSweep: "Sweep",
  revealFade: "Fade",
  revealHint: "Typewriter: paced by audio length; sweep: fixed layout; fade: sentence by sentence.",
  displaySecondsLabel: "Hold time",
  nameColorLabel: "Speaker colour",
  textColorLabel: "Text colour",
  rubyColorLabel: "Source colour",
  countdownColorLabel: "Countdown colour",
  toggleDialogLabel: "Toggle subtitles",
  toggleHoldLabel: "Toggle always-on",
  idleStopSecsLabel: "VRAM release delay",
  secondsUnit: "s",
  rubyHint: "Accepted formats: #rgb, #rrggbb or #aarrggbb (leading pair is the alpha channel).",
  hotkeyHint: "Must include a modifier (Ctrl/Alt/Shift), so global input is not swallowed.",
  idleStopHint:
    "After the delay the model cache is released; sustained idleness stops the engine process. 0 keeps the model resident.",
  serviceNote: "Takes effect at the next service start",
  defaultValue: "Default",
  historyEmpty: "No changes recorded",
  historyEmptyLead: "After any setting is changed, restorable entries appear here; they live in ",
  historyEmptyTail: ".",
  confirmRestore: "Confirm restore",
  cancel: "Cancel",
  restore: "Restore",
  restored: (file) => `${file} restored`,
  restoreFailed: (detail) => `Restoring failed: ${detail}`,
  loadFailed: (detail) => `Loading settings failed: ${detail}`,
  loadHistoryFailed: (detail) => `Loading the change history failed: ${detail}`,
  hotkeyFormat: "Hotkey format: modifier+key, e.g. Ctrl+Alt+D.",
};
