// The status screen, in both languages. `zh` is the source of truth; the `en` object
// types itself against it, so a key added above and forgotten below is a compile error.

export const statusZh = {
  title: "状态",
  service: "服务",
  metrics: "运行指标",
  env: "环境",
  guide: "使用说明",
  guideHint: "把其中一句粘贴给 agent，它自己去读技能文件。",
  checkEnv: "检查环境",

  startService: "启动服务",
  stopService: "停止服务",
  toggleFailed: (kind: string, detail: string) => `${kind}服务失败：${detail}`,
  start: "启动",
  stop: "停止",

  running: "运行中",
  stopped: "已停止",
  loaded: "已加载",
  notLoaded: "未加载",
  runtimeRow: "运行时服务",
  presenterRow: "字幕窗口",
  modelRow: "音色模型",
  uptime: (duration: string) => `运行时间 ${duration}`,
  unreachable: "运行时无响应",
  missingTitle: "存在缺失依赖或资源",

  engineStopped: "已停止",
  engineIdle: "空闲",
  engineStarting: "启动中",
  engineRunningNoModel: "运行中（模型未加载）",
  modelResident: "模型驻留中",
  vramReleased: "已释放",
  runtimeTile: "运行时服务",
  engineTile: "语音引擎",
  vramTile: "显存占用",
  vramTotal: (size: string) => `显卡总计 ${size}`,
  vramTotalNoPerProcess: "显卡总占用（显卡驱动未提供进程粒度指标）",
  vramTotalLabel: "显卡总占用",
  memTile: "内存占用",
  engineShare: (size: string) => `引擎占用 ${size}`,
  recycleTile: "自动回收",
  recycleOff: "未启用",
  idleFor: (duration: string) => `已空闲 ${duration}`,
  packsTile: "音色包",
  presentersTile: "字幕客户端",
  inflightTile: "并发请求",
  count: (n: number) => `${n} 个`,
  spoolLabel: "音频缓存池",

  engineSource: "引擎源码",
  pythonCuda: "Python 与 CUDA",
  weights: (have: number, total: number) => `模型权重 ${have} / ${total}`,
  packs: (n: number) => `音色包 ${n}`,
  ready: "就绪",
  missing: "缺失",
  dataDir: "数据目录",
  installDir: "安装目录",

  guideSpeakLabel: "日常出声",
  guideSpeakWhat: "日常出声的说明",
  guideSpeak: (root: string) =>
    `用 voice-core-tts 技能在这台机器上出声。没装这个技能就读 ${root}\\skills\\voice-core-tts\\SKILL.md，是同一份文件。`,
  guideTrainLabel: "训练新音色",
  guideTrainWhat: "训练新音色的说明",
  guideTrain: (root: string) =>
    `用 voice-core-voice-training 技能训练一个新音色包。没装这个技能就读 ${root}\\skills\\voice-core-voice-training\\SKILL.md，是同一份文件。`,
  guideDeployLabel: "环境部署与修复",
  guideDeployWhat: "环境部署与修复的说明",
  guideDeploy: (root: string) =>
    `用 voice-core-deploy 技能在第一次安装后配置环境、升级后修复或换机迁移。没装这个技能就读 ${root}\\skills\\voice-core-deploy\\SKILL.md，是同一份文件。`,

  notDeployed: "服务尚未部署",
  goDeploy: "前往部署",
};

export const statusEn: typeof statusZh = {
  title: "Status",
  service: "Service",
  metrics: "Metrics",
  env: "Environment",
  guide: "Usage",
  guideHint: "Paste one line to your agent; it reads the skill file itself.",
  checkEnv: "Check environment",
  startService: "Start service",
  stopService: "Stop service",
  toggleFailed: (kind, detail) => `Failed to ${kind} the service: ${detail}`,
  start: "start",
  stop: "stop",
  running: "Running",
  stopped: "Stopped",
  loaded: "Loaded",
  notLoaded: "Not loaded",
  runtimeRow: "Runtime service",
  presenterRow: "Subtitle window",
  modelRow: "Voice model",
  uptime: (duration) => `Uptime ${duration}`,
  unreachable: "Runtime not responding",
  missingTitle: "Missing dependencies or resources",
  engineStopped: "Stopped",
  engineIdle: "Idle",
  engineStarting: "Starting",
  engineRunningNoModel: "Running (model not loaded)",
  modelResident: "Model resident",
  vramReleased: "Released",
  runtimeTile: "Runtime service",
  engineTile: "Voice engine",
  vramTile: "VRAM",
  vramTotal: (size) => `GPU total ${size}`,
  vramTotalNoPerProcess: "GPU total (driver does not report per-process figures)",
  vramTotalLabel: "GPU total",
  memTile: "Memory",
  engineShare: (size) => `Engine ${size}`,
  recycleTile: "Auto unload",
  recycleOff: "Off",
  idleFor: (duration) => `Idle for ${duration}`,
  packsTile: "Voice packs",
  presentersTile: "Subtitle clients",
  inflightTile: "In-flight requests",
  count: (n) => `${n}`,
  spoolLabel: "Audio spool",
  engineSource: "Engine source",
  pythonCuda: "Python & CUDA",
  weights: (have, total) => `Model weights ${have} / ${total}`,
  packs: (n) => `Voice packs ${n}`,
  ready: "Ready",
  missing: "Missing",
  dataDir: "Data directory",
  installDir: "Install directory",
  guideSpeakLabel: "Everyday speech",
  guideSpeakWhat: "the everyday-speech instructions",
  guideSpeak: (root) =>
    `Speak on this machine with the voice-core-tts skill. If the skill is not installed, read ${root}\\skills\\voice-core-tts\\SKILL.md - it is the same file.`,
  guideTrainLabel: "Train a new voice",
  guideTrainWhat: "the voice-training instructions",
  guideTrain: (root) =>
    `Train a new voice pack with the voice-core-voice-training skill. If the skill is not installed, read ${root}\\skills\\voice-core-voice-training\\SKILL.md - it is the same file.`,
  guideDeployLabel: "Deploy & repair",
  guideDeployWhat: "the deployment instructions",
  guideDeploy: (root) =>
    `Set up the environment after the first install, repair it after an upgrade, or migrate machines with the voice-core-deploy skill. If the skill is not installed, read ${root}\\skills\\voice-core-deploy\\SKILL.md - it is the same file.`,
  notDeployed: "Service not deployed yet",
  goDeploy: "Go to deploy",
};
