// The training screen, in both languages. `zh` is the source of truth; the `en` object
// types itself against it, so a key added above and forgotten below is a compile error.
// The console's own words (ERROR, loss, step, ETA, and the Chinese words the emphasis
// regex matches inside process output) are the pipeline's vocabulary, not the panel's,
// and stay as written.

export const trainZh = {
  title: "训练",

  runsPanel: "训练运行",
  runsEmpty: "暂无训练运行",
  runsEmptyBody:
    "让 agent 按 voice-core-voice-training 技能执行训练，它每一步写下的状态文件会让这次运行出现在这里。",
  colPack: "音色包 ID",
  colStage: "阶段",
  colState: "状态",
  colUpdated: "更新于",
  ago: (duration: string) => `${duration} 前`,
  liveSentence: (stage: string, position: string) => `正在运行 · ${stage}${position}`,
  lastFailed: (stage: string) => `上次运行在阶段「${stage}」失败`,
  lastInterrupted: (stage: string) => `上次运行在阶段「${stage}」被中断`,
  lastUntil: (stage: string, state: string) => `上次运行至阶段「${stage}」· ${state}`,
  pidLine: (pid: number, ago: string) => `PID ${pid} · 更新于 ${ago} 前`,
  stderrHint: "标准错误流 (stderr) 中包含详细错误堆栈",

  progressPanel: "训练进度",
  follow: "跟随",
  stepAria: (index: number, label: string) => `步骤 ${index}：${label}`,
  doneCount: (n: number) => `已完成 ${n}`,

  resultsPanel: "训练成果",
  resultsHint: "已按验证损失升序排序，默认选中最优检查点",
  checkpointsEmpty: "暂无检查点生成",
  checkpointsEmptyBody: "模型训练过程中将按保存间隔生成检查点，评分阶段将追加相似度评估指标。",
  colCheckpoint: "检查点",
  colStep: "步数",
  colValLoss: "验证损失",
  colLowerBound: "相似度下界",
  installedChip: "已安装",

  filesPanel: "产物文件",
  filesCount: (label: string, n: number) => `${label} · ${n} 个文件`,
  notGenerated: "未生成",
  noScratch: "暂无暂存目录",
  logsKept: "日志文件（清理暂存区时将予以保留）",
  eventLog: "事件日志",
  statusData: "状态数据 (JSON)",
  discardRefusalTitle: "暂存目录中存在未安装的检查点",
  confirmDiscard: "确认清理并删除未保存检查点",
  discardScratch: "清理暂存",
  discardBlocked: "该音色包正在训练",

  installingNow: "正在安装音色包",
  pickRunFirst: "请先选择一次训练运行",
  noCheckpoint: "本次运行尚无可安装的检查点",
  refresh: "刷新",
  reinstall: "重新安装",
  installAsPack: "安装为音色包",
  installedToast: (id: string) => `音色包 ${id} 已安装，将在下次服务加载时生效`,
  discardedToast: (id: string, freed: string) => `已清理 ${id} 的暂存目录，释放存储空间 ${freed}`,

  // The six steps, named by what they produce.
  stageDataset: "语料校验",
  stageLatents: "音频特征提取",
  stageTrain: "训练适配器",
  stageSamples: "生成试听样本",
  stageScore: "音色相似度评分",
  stageInstall: "安装音色包",

  hintDataset: "dataset.jsonl 与质检报告",
  hintLatents: "DACVAE 潜变量 (.pt) 与训练清单",
  hintTrain: "LoRA 权重训练（高 GPU 负载阶段）",
  hintSamples: "固定随机种子 · 每个检查点各一组样本",
  hintScore: "GE2E d-vector · CPU",
  hintInstall: "归档检查点并生成 voicepack.json",

  statePending: "待执行",
  stateRunning: "进行中",
  stateOk: "已完成",
  stateSkip: "已跳过",
  stateFail: "失败",
  stateInterrupted: "已中断",

  artefactDataset: "数据集清单 (dataset.jsonl)",
  artefactQa: "语料质检报告 (dataset.jsonl.qa.json)",
  artefactManifest: "训练样本清单 (train_manifest.jsonl)",
  artefactLatents: "潜变量特征目录 (latents)",
  artefactLora: "模型检查点目录 (lora)",
  artefactSamples: "试听音频样本 (samples)",
  artefactScore: "相似度评估报告 (score)",
  artefactInstalled: "安装记录 (installed.txt)",
};

export const trainEn: typeof trainZh = {
  title: "Train",
  runsPanel: "Training runs",
  runsEmpty: "No training runs",
  runsEmptyBody:
    "Have your agent run training with the voice-core-voice-training skill; the status file it writes at every step puts the run here.",
  colPack: "Pack ID",
  colStage: "Stage",
  colState: "State",
  colUpdated: "Updated",
  ago: (duration) => `${duration} ago`,
  liveSentence: (stage, position) => `Running · ${stage}${position}`,
  lastFailed: (stage) => `The last run failed at "${stage}"`,
  lastInterrupted: (stage) => `The last run was interrupted at "${stage}"`,
  lastUntil: (stage, state) => `The last run reached "${stage}" · ${state}`,
  pidLine: (pid, ago) => `PID ${pid} · updated ${ago}`,
  stderrHint: "The standard error stream (stderr) carries the full stack trace",
  progressPanel: "Progress",
  follow: "Follow",
  stepAria: (index, label) => `Step ${index}: ${label}`,
  doneCount: (n) => `${n} done`,
  resultsPanel: "Results",
  resultsHint: "Sorted by validation loss; the best checkpoint is selected by default",
  checkpointsEmpty: "No checkpoints yet",
  checkpointsEmptyBody:
    "Checkpoints are written at the save interval during training; the scoring stage appends similarity metrics.",
  colCheckpoint: "Checkpoint",
  colStep: "Step",
  colValLoss: "Val loss",
  colLowerBound: "Similarity lower bound",
  installedChip: "Installed",
  filesPanel: "Artefacts",
  filesCount: (label, n) => `${label} · ${n} files`,
  notGenerated: "Not produced",
  noScratch: "No scratch tree yet",
  logsKept: "Log files (kept when the scratch tree is discarded)",
  eventLog: "Event log",
  statusData: "Status data (JSON)",
  discardRefusalTitle: "The scratch tree holds uninstalled checkpoints",
  confirmDiscard: "Discard and delete unsaved checkpoints",
  discardScratch: "Discard scratch",
  discardBlocked: "This pack is currently training",
  installingNow: "Installing the voice pack",
  pickRunFirst: "Select a training run first",
  noCheckpoint: "This run has no installable checkpoint yet",
  refresh: "Refresh",
  reinstall: "Reinstall",
  installAsPack: "Install as voice pack",
  installedToast: (id) => `Voice pack ${id} installed; it loads at the next service start`,
  discardedToast: (id, freed) => `Discarded the scratch tree for ${id}, freeing ${freed}`,
  stageDataset: "Dataset check",
  stageLatents: "Audio features",
  stageTrain: "Adapter training",
  stageSamples: "Sample synthesis",
  stageScore: "Similarity scoring",
  stageInstall: "Pack install",
  hintDataset: "dataset.jsonl and its QA report",
  hintLatents: "DACVAE latents (.pt) and the training manifest",
  hintTrain: "LoRA weight training (high GPU load)",
  hintSamples: "Fixed seed · one sample set per checkpoint",
  hintScore: "GE2E d-vector · CPU",
  hintInstall: "Archive checkpoints and write voicepack.json",
  statePending: "Pending",
  stateRunning: "Running",
  stateOk: "Done",
  stateSkip: "Skipped",
  stateFail: "Failed",
  stateInterrupted: "Interrupted",
  artefactDataset: "Dataset manifest (dataset.jsonl)",
  artefactQa: "Corpus QA report (dataset.jsonl.qa.json)",
  artefactManifest: "Training manifest (train_manifest.jsonl)",
  artefactLatents: "Latent features (latents)",
  artefactLora: "Model checkpoints (lora)",
  artefactSamples: "Audition samples (samples)",
  artefactScore: "Similarity report (score)",
  artefactInstalled: "Install record (installed.txt)",
};
