// One voice pack's editing page, in both languages. `zh` is the source of truth; the `en`
// object types itself against it, so a key added above and forgotten below is a compile
// error. The preview line and the greeting it renders are content, not chrome, and stay
// as written.

export const voiceZh = {
  backToList: "返回音色列表",
  backTitle: "返回 (Esc)",

  identity: "身份信息",
  style: "字幕样式",
  styleHint: "未配置项将继承全局设置",
  synthesis: "合成参数",
  expression: "情绪控制",
  audition: "语音试听",
  openPackDir: "在文件资源管理器中打开音色包目录",

  provPackHint: "当前属性由音色包内的 voicepack.json 定义。",
  provConfigHint: "当前属性由全局 config.json 注册项定义；保存后将转由音色包自身配置管理。",
  provDerivedHint: "当前属性使用系统默认或推导值；保存后将写入音色包自身配置。",

  blockedLoading: "正在加载音色包配置…",
  blockedReadonly: "音色包所在路径为只读介质或受限网络共享，无法写入修改。",

  manifestOk: "独立配置 (voicepack.json)",
  manifestInit: "未初始化配置（首次保存时自动生成）",

  nameLabel: "显示名称",
  nameEmpty: "显示名称不能为空",
  characterLabel: "角色名称",
  characterHint: "字幕窗口展示的说话人名称；留空时默认采用音色包名称。",
  kindLabel: "模型类型",
  languagesLabel: "支持语言",
  languagesHint: "服务运行时将校验请求语言，拒绝未匹配语种的合成请求。",
  languagesPlaceholder: "添加语种代码（如 ja）",
  languagesEmpty: "请至少指定一种语言代码（如 ja）",
  engineLabel: "推理引擎",
  engineHint: "引擎标识标签；针对 Irodori 架构请填写 irodori。",
  engineEmpty: "推理引擎不能为空",
  avatarLabel: "头像图标",
  avatarHint: "头像文件将归档至音色包目录，便于整体打包迁移。",
  avatarPick: "选择图像…",

  coloursGroup: "配色方案",
  nameColorLabel: "说话人颜色",
  textColorLabel: "正文文本颜色",
  rubyColorLabel: "发音原文颜色",
  rubyColorHint: "格式支持 #rgb、#rrggbb 或 #aarrggbb（前两位为透明度通道）。",
  countdownColorLabel: "倒计时条颜色",
  motionGroup: "动效与停留",
  revealLabel: "文字动效",
  revealTypewriter: "打字机",
  revealSweep: "扫光",
  revealFade: "淡入",
  inheritGlobal: "继承全局",
  displaySecondsLabel: "停留时间",
  secondsUnit: "秒",

  stepsLabel: "推理步数 (Steps)",
  stepsHint: "采样迭代步数：数值越高生成质量越稳定，耗时相应增加；默认值为 32。",
  seedLabel: "随机种子 (Seed)",
  seedHint: "固定随机种子可确保相同文本生成一致的音频表现。",
  seedPlaceholder: "随机生成 (-1)",
  temperaturePlaceholder: "使用引擎默认值",

  emotionLabel: "情绪标记",
  emotionHint:
    "支持在待念文本中嵌入情绪标记，重复输入可增强情绪表达：😆 喜び 😭 嗚咽 😱 悲鳴 😖 苦しげ 🥺 震え声 👂 囁き ⏩ 早口 🐢 ゆっくり 🤭 笑い 🫶 優しく",
  emotionPlaceholder: "输入表情符号（如 😭😭）",
  cfgLabel: "情绪引导强度 (CFG Scale)",
  cfgHint: "cfgScaleCaption 参数，默认值为 3.0；数值越高对上方情绪标签的贴合越强。",

  auditionInput: "试听文本输入",
  auditionGo: "试听合成",
  auditionNotRunning: "运行时服务未启动，请前往「状态」页面启动服务后再进行试听。",
  auditionBusy: "正在合成音频…",
  auditionResult: (seconds: string, kib: string, ms: number) =>
    `${seconds} 秒音频 · ${kib} KiB · 耗时 ${ms} ms`,
  auditionCold: "（含模型冷启动）",
  auditionNoPresenter:
    "音频合成完成；当前未检测到活跃的字幕客户端，未触发本地播放。启动字幕端后重试即可收听。",

  loadFailed: (detail: string) => `加载音色包配置失败：${detail}`,
  notFound: "音色包未找到",
  notFoundBody: (id: string) => `注册表中未找到音色包 ID：${id}。`,

  kindLora: "LoRA 适配器",
  kindEmbedding: "说话人嵌入",
  kindReference: "参考音频",
};

export const voiceEn: typeof voiceZh = {
  backToList: "Back to the voice list",
  backTitle: "Back (Esc)",
  identity: "Identity",
  style: "Subtitle style",
  styleHint: "Unset fields inherit the global settings",
  synthesis: "Synthesis",
  expression: "Emotion",
  audition: "Audition",
  openPackDir: "Open the voice-pack folder in File Explorer",
  provPackHint: "This field is defined by the pack's own voicepack.json.",
  provConfigHint:
    "This field is defined by the global config.json registry entry; saving here moves it under the pack's own config.",
  provDerivedHint:
    "This field uses a system default or a derived value; saving writes it into the pack's own config.",
  blockedLoading: "Loading the voice pack's config…",
  blockedReadonly:
    "The voice pack sits on read-only media or a restricted network share; changes cannot be written.",
  manifestOk: "Own config (voicepack.json)",
  manifestInit: "Not initialised (generated on first save)",
  nameLabel: "Display name",
  nameEmpty: "The display name cannot be empty",
  characterLabel: "Character name",
  characterHint: "The speaker name shown in the subtitle window; defaults to the pack's name when empty.",
  kindLabel: "Model type",
  languagesLabel: "Languages",
  languagesHint: "The runtime validates the requested language and rejects synthesis in a language the pack does not list.",
  languagesPlaceholder: "Add a language code (e.g. ja)",
  languagesEmpty: "Specify at least one language code (e.g. ja)",
  engineLabel: "Inference engine",
  engineHint: "The engine's identifier tag; use irodori for the Irodori architecture.",
  engineEmpty: "The inference engine cannot be empty",
  avatarLabel: "Avatar",
  avatarHint: "The avatar file is archived into the pack's folder, so the pack travels as one unit.",
  avatarPick: "Choose image…",
  coloursGroup: "Colours",
  nameColorLabel: "Speaker colour",
  textColorLabel: "Text colour",
  rubyColorLabel: "Source colour",
  rubyColorHint: "Accepted formats: #rgb, #rrggbb or #aarrggbb (leading pair is the alpha channel).",
  countdownColorLabel: "Countdown colour",
  motionGroup: "Motion & hold",
  revealLabel: "Text effect",
  revealTypewriter: "Typewriter",
  revealSweep: "Sweep",
  revealFade: "Fade",
  inheritGlobal: "Inherit global",
  displaySecondsLabel: "Hold time",
  secondsUnit: "s",
  stepsLabel: "Inference steps",
  stepsHint: "Sampling iterations: more steps are steadier and slower; the default is 32.",
  seedLabel: "Seed",
  seedHint: "A fixed seed produces the same audio for the same text.",
  seedPlaceholder: "Random (-1)",
  temperaturePlaceholder: "Engine default",
  emotionLabel: "Emotion markers",
  emotionHint:
    "Emoji markers can be embedded in the spoken text; repeating one strengthens it: 😆 喜び 😭 嗚咽 😱 悲鳴 😖 苦しげ 🥺 震え声 👂 囁き ⏩ 早口 🐢 ゆっくり 🤭 笑い 🫶 優しく",
  emotionPlaceholder: "Type emoji (e.g. 😭😭)",
  cfgLabel: "Emotion guidance (CFG Scale)",
  cfgHint: "The cfgScaleCaption parameter; the default is 3.0, and higher values follow the emotion tags above more closely.",
  auditionInput: "Audition text input",
  auditionGo: "Synthesise",
  auditionNotRunning:
    "The runtime service is not up; start it on the Status page, then audition again.",
  auditionBusy: "Synthesising…",
  auditionResult: (seconds, kib, ms) => `${seconds} s of audio · ${kib} KiB · ${ms} ms`,
  auditionCold: " (including model cold start)",
  auditionNoPresenter:
    "Synthesis finished; no active subtitle client was detected, so nothing played locally. Start the subtitle end and try again to hear it.",
  loadFailed: (detail) => `Loading the voice pack's config failed: ${detail}`,
  notFound: "Voice pack not found",
  notFoundBody: (id) => `No voice pack with the ID ${id} is in the registry.`,
  kindLora: "LoRA adapter",
  kindEmbedding: "Speaker embedding",
  kindReference: "Reference audio",
};
